In [70]:
import numpy as np
import pandas as pd

In [71]:
tab = np.array(([0, 1, 2, 3, 4], [12, 20, 5, 2, 1]))
tab

array([[ 0,  1,  2,  3,  4],
       [12, 20,  5,  2,  1]])

In [72]:
effectif_cum_crois = tab.cumsum(axis=1)
effectif_cum_crois = effectif_cum_crois[1, :]
effectif_cum_crois

array([12, 32, 37, 39, 40])

In [73]:
tab2 = tab[1, -1:-6:-1]
effectif_cum_dec = np.array([])
som = 0
for i in tab2:
    som = som + i
    effectif_cum_dec = np.append(effectif_cum_dec , np.array([som]), axis = 0)
effectif_cum_dec = effectif_cum_dec[::-1]
effectif_cum_dec

array([40., 28.,  8.,  3.,  1.])

In [74]:
# frequence = ni / n * 100
ni = tab[1]
frequence = (ni / ni.sum()) * 100
frequence

array([30. , 50. , 12.5,  5. ,  2.5])

In [75]:
# frequenc cumulé croissant
fcc = effectif_cum_crois / ni.sum() * 100
fcc

array([ 30. ,  80. ,  92.5,  97.5, 100. ])

In [88]:
# frequence cumulé decroissant 
fcd = effectif_cum_dec / ni.sum() * 100
fcd

array([100. ,  70. ,  20. ,   7.5,   2.5])

In [89]:
tabf = np.vstack((tab ,effectif_cum_crois,  effectif_cum_dec , frequence, fcc , fcd))
tabf

array([[  0. ,   1. ,   2. ,   3. ,   4. ],
       [ 12. ,  20. ,   5. ,   2. ,   1. ],
       [ 12. ,  32. ,  37. ,  39. ,  40. ],
       [ 40. ,  28. ,   8. ,   3. ,   1. ],
       [ 30. ,  50. ,  12.5,   5. ,   2.5],
       [ 30. ,  80. ,  92.5,  97.5, 100. ],
       [100. ,  70. ,  20. ,   7.5,   2.5]])

In [90]:
pd.DataFrame({'0': tabf[1:, 0], '1': tabf[1:, 1], '2': tabf[1:, 2], '3': tabf[1:, 3], '4': tabf[1:, 4]} , index = ['ni','nic','nid','fi(%)','fic(%)', 'fid(%)'])

0     1     2     3      4
ni       12.0  20.0   5.0   2.0    1.0
nic      12.0  32.0  37.0  39.0   40.0
nid      40.0  28.0   8.0   3.0    1.0
fi(%)    30.0  50.0  12.5   5.0    2.5
fic(%)   30.0  80.0  92.5  97.5  100.0
fid(%)  100.0  70.0  20.0   7.5    2.5